#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.3.3 effective-5.10 (swiftlang-6.3.3.1.3 clang-2100.1.1.101)
#ifndef APPIERADS_SWIFT_H
#define APPIERADS_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AppierAds",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AppierAds",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

SWIFT_ENUM_FWD_DECL(NSInteger, APRDataKey)
SWIFT_CLASS("_TtC9AppierAds11APRAdExtras")
@interface APRAdExtras : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)setWithKey:(enum APRDataKey)key value:(id _Nonnull)value;
- (id _Nullable)getWithKey:(enum APRDataKey)key SWIFT_WARN_UNUSED_RESULT;
@end

@class NSString;
SWIFT_PROTOCOL("_TtP9AppierAds19APRAdUnitIdentifier_")
@protocol APRAdUnitIdentifier
- (NSString * _Nonnull)get SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS("_TtC9AppierAds11APRAdUnitId")
@interface APRAdUnitId : NSObject <APRAdUnitIdentifier>
- (nonnull instancetype)init:(NSString * _Nonnull)adUnitId OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nonnull)get SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class APRAdsConfiguration;
SWIFT_CLASS("_TtC9AppierAds6APRAds")
@interface APRAds : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) APRAds * _Nonnull shared;)
+ (APRAds * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
+ (void)setShared:(APRAds * _Nonnull)value;
@property (nonatomic, strong) APRAdsConfiguration * _Nonnull configuration;
@property (nonatomic, readonly, copy) NSString * _Nonnull version;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (void)startWithCompletion:(void (^ _Nullable)(BOOL))completion;
@end

SWIFT_ENUM_FWD_DECL(NSInteger, APRTestMode)
SWIFT_ENUM_FWD_DECL(NSInteger, APRBrowserAgent)
SWIFT_CLASS("_TtC9AppierAds19APRAdsConfiguration")
@interface APRAdsConfiguration : NSObject
@property (nonatomic) enum APRTestMode testMode;
@property (nonatomic) enum APRBrowserAgent browserAgent;
@property (nonatomic) BOOL coppaApplies;
@property (nonatomic) BOOL gdprApplies;
@property (nonatomic) BOOL forceGDPRApplies;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, APRBrowserAgent, open) {
  APRBrowserAgentNative = 0,
};

typedef SWIFT_ENUM(NSInteger, APRDataKey, open) {
  APRDataKeyAdUnitId = 0,
  APRDataKeyZoneId = 1,
  APRDataKeyAdWidth = 2,
  APRDataKeyAdHeight = 3,
  APRDataKeyAdOrientation = 4,
  APRDataKeyAppInfo = 5,
};

SWIFT_ENUM_FWD_DECL(NSInteger, APRErrorType)
SWIFT_CLASS("_TtC9AppierAds8APRError")
@interface APRError : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)initWithType:(enum APRErrorType)type OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, APRErrorType, open) {
  APRErrorTypeNoBid = 0,
  APRErrorTypeZoneIdError = 1,
  APRErrorTypeAdUnitIdError = 2,
  APRErrorTypeNetworkError = 3,
  APRErrorTypeBadRequest = 4,
  APRErrorTypeInternalServerError = 5,
  APRErrorTypeInvalidJson = 6,
  APRErrorTypeWebViewError = 7,
  APRErrorTypeVideoPlaybackError = 8,
  APRErrorTypeVideoFileError = 9,
  APRErrorTypeFetchImageError = 10,
  APRErrorTypeUnknownError = 11,
  APRErrorTypeDataConvertError = 12,
  APRErrorTypeRequestNotExist = 13,
};

SWIFT_CLASS("_TtC9AppierAds9APRLogger")
@interface APRLogger : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull category;
@property (nonatomic, readonly) BOOL enable;
- (nonnull instancetype)initWithCategory:(NSString * _Nonnull)category OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface APRLogger (SWIFT_EXTENSION(AppierAds))
- (void)debugLog:(NSString * _Nonnull)message;
- (void)infoLog:(NSString * _Nonnull)message;
- (void)warningLog:(NSString * _Nonnull)message;
- (void)errorLog:(NSString * _Nonnull)message;
@end

SWIFT_CLASS("_TtC9AppierAds12AppierBaseAd")
@interface AppierBaseAd : NSObject
- (void)setWithExtras:(APRAdExtras * _Nonnull)extras;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol APRNativeAdDelegate;
@class UIImage;
@protocol APRNativeAdRendering;
@class UIView;
SWIFT_CLASS("_TtC9AppierAds11APRNativeAd")
@interface APRNativeAd : AppierBaseAd
@property (nonatomic, weak) id <APRNativeAdDelegate> _Nullable delegate;
@property (nonatomic, readonly, copy) NSString * _Nullable title;
@property (nonatomic, readonly, copy) NSString * _Nullable mainText;
@property (nonatomic, readonly, copy) NSString * _Nullable callToAction;
@property (nonatomic, strong) UIImage * _Nullable iconImage;
@property (nonatomic, strong) UIImage * _Nullable mainImage;
@property (nonatomic, strong) UIImage * _Nullable privacyInformationImage;
- (nonnull instancetype)initWithAdUnitId:(id <APRAdUnitIdentifier> _Nonnull)adUnitId OBJC_DESIGNATED_INITIALIZER;
/// The ad holds <code>renderer</code> weakly, so the caller must keep its own strong
/// reference for as long as the ad should render into it.
- (void)setWithRenderer:(id <APRNativeAdRendering> _Nonnull)renderer;
- (void)loadAd;
/// Records the outer native impression. <em>The only way an impression is
/// ever recorded</em> — the SDK no longer triggers one by itself. (MT-9349)
/// The host owns the decision because only the host can see it: under
/// mediation the GMA SDK runs its own viewability check and tells the
/// adapter through <code>didRecordImpression()</code>; on direct integration the app
/// knows when it put the ad on screen. Everything the SDK could observe from
/// the inside — assets rendered into outlets, a media view constructed —
/// happens before anyone has seen the ad, and billing runs off this beacon.
/// Previously <code>render()</code> and <code>makeVideoAdView()</code> each recorded it, and the
/// guard sat in a private wrapper that this public method bypassed. On the
/// mediation video path that meant two impressions for one ad: one when the
/// adapter built the media view, one from GMA’s callback.
/// At most once per delivered creative: a rebound cell or a reload that
/// fails cannot re-count the creative on screen. Normalised onto the main
/// thread like <code>loadAd()</code>, so the gate is not read and written from two
/// queues at once. Objective-C hosts call it as <code>-recordImpression</code>.
- (void)recordImpression;
- (void)render;
/// Whether the loaded creative carries a playable video (vs image-only).
@property (nonatomic, readonly) BOOL hasVideoContent;
/// width / height of the video, 0 when there is no video or the size is
/// unknown. GMA uses it to lay out the media area.
@property (nonatomic, readonly) CGFloat mediationVideoAspectRatio;
/// Total length in seconds, 0 when there is no video or it is unknown.
@property (nonatomic, readonly) NSTimeInterval mediationVideoDuration;
/// Seconds played so far, 0 before anything plays.
@property (nonatomic, readonly) NSTimeInterval mediationVideoCurrentTime;
/// Permanently stops this ad’s video component. View untracking is not
/// destruction: mediation should call <code>untrackAdView()</code> when recycling.
- (void)teardownVideoAdView;
/// Returns this ad’s media surface, the same view on every call, retaining
/// playback state across reuse. Main thread only; <code>nil</code> for an image-only
/// creative. Creation emits neither an impression nor a playback start.
/// Taps on the video are this view’s own ad click.
- (UIView * _Nullable)makeVideoAdView SWIFT_WARN_UNUSED_RESULT;
/// The same media surface as <code>makeVideoAdView()</code>, for a mediation adapter
/// whose network tracks clicks on its own media view (GMA): taps on the
/// video, other than its controls, fall through to the host view, and the
/// network hands the click back for the adapter to forward to
/// <code>clickAdView()</code>. The beacons sent are the same either way. (MT-9341)
- (UIView * _Nullable)makeMediationVideoAdView SWIFT_WARN_UNUSED_RESULT;
- (void)clickAdViewWithSender:(id _Nullable)sender;
- (void)clickPrivacyInformationViewWithSender:(id _Nullable)sender;
/// Ends the SKAdNetwork impression. Untracking is not destruction: the video
/// component and its state stay for a later rebind.
- (void)untrackAdView;
@end

SWIFT_PROTOCOL("_TtP9AppierAds19APRNativeAdDelegate_")
@protocol APRNativeAdDelegate
- (void)onAdLoaded:(APRNativeAd * _Nonnull)nativeAd;
- (void)onAdLoadedFailed:(APRNativeAd * _Nonnull)nativeAd error:(APRError * _Nonnull)error;
- (void)onAdNoBid:(APRNativeAd * _Nonnull)nativeAd;
- (void)onAdShown:(APRNativeAd * _Nonnull)nativeAd;
- (void)onAdImpressionRecorded:(APRNativeAd * _Nonnull)nativeAd;
- (void)onAdImpressionRecordedFailed:(APRNativeAd * _Nonnull)nativeAd error:(APRError * _Nonnull)error;
- (void)onAdClickedRecorded:(APRNativeAd * _Nonnull)nativeAd;
- (void)onAdClickedRecordedFailed:(APRNativeAd * _Nonnull)nativeAd error:(APRError * _Nonnull)error;
@optional
/// Playback actually started for the first time. Showing a first-frame
/// preview is not a start. Fires once per creative.
- (void)onVideoStart:(APRNativeAd * _Nonnull)nativeAd;
/// Playback that had started actually paused: the view dropped below 45%
/// visible, the app went to the background, or the player paused itself.
/// Not sent for a natural end or when the component is destroyed.
- (void)onVideoPause:(APRNativeAd * _Nonnull)nativeAd;
/// Paused playback actually resumed from its saved position.
- (void)onVideoResume:(APRNativeAd * _Nonnull)nativeAd;
/// Playback reached its natural end. Fires once; the video never replays.
- (void)onVideoComplete:(APRNativeAd * _Nonnull)nativeAd;
/// The effective mute state changed; <code>muted</code> is the new value. Every
/// creative starts muted.
- (void)onVideoMuteChanged:(APRNativeAd * _Nonnull)nativeAd muted:(BOOL)muted;
/// The video failed: at load time (the load also fails) or after delivery
/// (the surface degrades to the poster or last frame and stays clickable).
/// <code>code</code> is the error beacon’s <code>ERRORCODE</code>, e.g. “400” or “405”.
- (void)onVideoError:(APRNativeAd * _Nonnull)nativeAd code:(NSString * _Nonnull)code;
@end

@class UILabel;
@class UIImageView;
/// The APRNativeAdRendering protocol provides methods for displaying ad content in custom view classes.
SWIFT_PROTOCOL("_TtP9AppierAds20APRNativeAdRendering_")
@protocol APRNativeAdRendering
/// UILabel that your view is using for the title.
@property (nonatomic, readonly, strong) UILabel * _Nullable nativeAdTitleLabel;
/// UILabel that your view is using for the main text.
@property (nonatomic, readonly, strong) UILabel * _Nullable nativeAdMainTextLabel;
/// UILabel that your view is using for the call to action (cta).
@property (nonatomic, readonly, strong) UILabel * _Nullable nativeAdCallToActionLabel;
/// UIImageView that your view is using for the icon image.
@property (nonatomic, readonly, strong) UIImageView * _Nullable nativeAdIconImageView;
/// UIImageView that your view is using for the main image.
@property (nonatomic, readonly, strong) UIImageView * _Nullable nativeAdMainImageView;
/// UIView that your view is using for the privacy information icon image.
@property (nonatomic, readonly, strong) UIView * _Nullable nativeAdPrivacyInformationIconView;
/// Return the array of UIView instances that may be clickable.
/// In some cases, especially in view subclasses that have a complex view hierarchy,
/// it may be desirable to specify a subset of views that are considered clickable.
/// Supply these views here.
/// <ul>
///   <li>
///     return: an array of UIView instances.
///   </li>
/// </ul>
- (NSArray<UIView *> * _Nonnull)getNativeAdClickableViews SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM(NSInteger, APRTestMode, open) {
  APRTestModeNone = 0,
  APRTestModeBid = 1,
  APRTestModeNoBid = 2,
  APRTestModeBidWithStoreView = 3,
};

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
