# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do
    setup_circle_ci
  end

  desc "Open GitHub Ads SDK pull request"
  lane :pr_ads_sdk do |options|
    branch_name = options.fetch(:branch_name, "release_ads_sdk")
    framework_version = get_framework_version_ads_sdk

    # Set Podspec version
    version_file = {
      "version" => "v#{framework_version}"
    }

    File.write("../version_ads_sdk.json", version_file.to_json)

    # Commit and push changes
    sh "git checkout -b #{branch_name}"

    path = [
      "./AppierAds.xcframework/*",
      "./version_ads_sdk.json"
    ]

    git_add(
      path: path
    )

    git_commit(
      path: path,
      message: "Release Ads SDK #{framework_version}"
    )

    push_to_git_remote(
      force: true,
      local_branch: branch_name,
      remote_branch: branch_name
    )

    # Open pull request
    github_api(
      server_url: "https://api.github.com",
      api_token: ENV["GITHUB_TOKEN"],
      http_method: "POST",
      path: "/repos/appier/ads-ios-sdk/pulls",
      body: {
        "head": branch_name,
        "base": "main",
        "title": "Release Ads SDK v#{framework_version}"
      }
    )
  end

  desc "Deploy Ads SDK Podspecs to CocoaPods Trunk"
  lane :pods_ads_sdk do
    Dir.chdir("..") do
      sh "pod trunk push AppierAds.podspec --allow-warnings"
    end
  end

  desc "Create Ads SDK release on GitHub"
  lane :release_ads_sdk do
    framework_version = get_framework_version_ads_sdk
    tag = "ads-sdk-v#{framework_version}"
    archive_name = "AppierAdsFramework.zip"

    Dir.chdir("..") do
      sh "zip -r #{archive_name} AppierAds.xcframework"
    end

    github_release = set_github_release(
      repository_name: "appier/ads-ios-sdk",
      api_token: ENV["GITHUB_TOKEN"],
      name: "Appier Ads iOS SDK #{framework_version}",
      tag_name: tag,
      description: "",
      commitish: "main",
      upload_assets: [
        archive_name
      ]
    )
  end

  desc "Open GitHub Admob Mediation pull request"
  lane :pr_admob_mediation do |options|
    branch_name = options.fetch(:branch_name, "release_admob_mediation")
    framework_version = get_framework_version_admob_mediation

    # Set Podspec version
    version_file = {
      "version" => "v#{framework_version}"
    }

    File.write("../version_admob_mediation.json", version_file.to_json)

    # Commit and push changes
    sh "git checkout -b #{branch_name}"

    path = [
      "./AppierAdsAdMobMediation.xcframework/*",
      "./version_admob_mediation.json"
    ]

    git_add(
      path: path
    )

    git_commit(
      path: path,
      message: "Release Admob Mediation #{framework_version}"
    )

    push_to_git_remote(
      force: true,
      local_branch: branch_name,
      remote_branch: branch_name
    )

    # Open pull request
    github_api(
      server_url: "https://api.github.com",
      api_token: ENV["GITHUB_TOKEN"],
      http_method: "POST",
      path: "/repos/appier/ads-ios-sdk/pulls",
      body: {
        "head": branch_name,
        "base": "main",
        "title": "Release Admob Mediation v#{framework_version}"
      }
    )
  end

  desc "Deploy Admob Mediation Podspecs to CocoaPods Trunk"
  lane :pods_admob_mediation do
    Dir.chdir("..") do
      sh "pod trunk me"
      sh "pod trunk push AppierAdsAdMobMediation.podspec --allow-warnings"
    end
  end

  desc "Create Admob Mediation release on GitHub"
  lane :release_admob_mediation do
    framework_version = get_framework_version_admob_mediation
    tag = "admob-mediation-v#{framework_version}"
    archive_name = "AppierAdMobMediationFramework.zip"

    Dir.chdir("..") do
      sh "zip -r #{archive_name} AppierAdsAdMobMediation.xcframework"
    end

    github_release = set_github_release(
      repository_name: "appier/ads-ios-sdk",
      api_token: ENV["GITHUB_TOKEN"],
      name: "Appier Admob Mediation iOS SDK #{framework_version}",
      tag_name: tag,
      description: "",
      commitish: "main",
      upload_assets: [
        archive_name
      ]
    )
  end

  private_lane :get_framework_version_ads_sdk do
    plist_file = "../AppierAds.xcframework/ios-arm64/AppierAds.framework/Info.plist"
    sh("/usr/libexec/PlistBuddy #{plist_file} -c 'Print :CFBundleShortVersionString'").strip
  end

  private_lane :get_framework_version_admob_mediation do
    plist_file = "../AppierAdsAdMobMediation.xcframework/ios-arm64/AppierAdsAdMobMediation.framework/Info.plist"
    sh("/usr/libexec/PlistBuddy #{plist_file} -c 'Print :CFBundleShortVersionString'").strip
  end

end
